### ISSUE TITLE
Filter by EventCategory in addition to HostId

### ISSUE THREAD

**Issue by ursbraem** [ursbraem/kursausschreibung#1]
We want to allow different lists than only by HostId.
Most importanty, lists filtered by EventCategoryIds.

Or, in German:

> Im Moment ist es nur möglich, nach der HostId (Veranstalter) zu filtern, das werden die obigen Begriffe sein wie Kurs WB Zebra.
> Wir möchten aber mindestens nach "EventCategory" (Kategorie) filtern können, damit ihr – nur als Beispiel – eine Liste mit allen Sprachkursen (EventCategory 1023) auf einer Seite anzeigen könnt.

**Comment by ursbraem** [comment]
So, I did https://github.com/ursbraem/kursausschreibung/commit/e80b416b47839b5591d1eed6c7164ac978b59512 on the branch feature/more_filters

Now it only has to work 😄

**Comment by cepheiVV** [comment]
code works just fine. only a small typo in object access by property `HostIds`.
`HostIds` should be uppercase in `settings.initialListFilters.HostIds`.

**Comment by ursbraem** [comment]
Also, 

"initialListFilters": {
    "HostIds": ['BB'],
    "EventCategoryIds": [1023,1010],
    "EventLevelIds": null,
    "EventTypeIds": null,
    "StatusIds": null,
  },

works in combination, returns only 4 courses, all 1010 & BB

**Comment by ursbraem** [comment]
merged & solved
